apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellow-kubernetes
  labels:
    app: hellow-kubernetes
template:
  spec:
    containers:
    - name: nginx
      image: paulbouwer/hello-kubernetes
      ports:
      - containerPort: 8080
