apiVersion: v1
kind: Service
metadata:
  name: hellow-kubernetesservice
  namespace: hello-kubernetes-ns
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 80