apiVersion: v1
kind: Service
metadata:
  name: hellow-kubernetes–svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80